//
//  DetailInteractor.swift
//  mApp
//
//  Created by Bahadır Enes Atay on 26.07.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailBusinessLogic {
    func getDetail(request: ContentDetailRequest)
}

class DetailInteractor {
    var presenter: DetailPresentationLogic?

}

extension DetailInteractor: DetailBusinessLogic {
    func getDetail(request: ContentDetailRequest) {
        DetailWorker().getSelectedMovie(request) { [weak self] response in
            self?.presenter?.presentDetail(response: Detail.FetchRequest.Response(content: response))
        } onError: { [weak self] error in
            self?.presenter?.presentError(error)
        }
    }
}

