//
//  DetailWorker.swift
//  mApp
//
//  Created by Bahadır Enes Atay on 26.07.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class DetailWorker {
    func getSelectedMovie(_ req: ContentDetailRequest, onSuccess: @escaping (ContentDetailResponse) -> Void, onError: @escaping (String) -> Void) {
        RequestManager.get(.series, ContentDetailResponse.self, req.toJSON()) { response, error in
            guard error == nil else {
                onError(error!.localizedDescription)
                return }
            if let response = response {
                onSuccess(response)
            } else {
                onError(APIError.dataNotFound.localizedDescription)
            }
        }
    }
}
