//
//  DetailRouter.swift
//  mApp
//
//  Created by Bahadır Enes Atay on 26.07.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailRoutingLogic {
    func navigate(from source: BaseViewController, to destination: BaseViewController)
    func present(from source: BaseViewController, to destination: BaseViewController)
}

class DetailRouter: NSObject {
    weak var viewController: DetailViewController?

}

extension DetailRouter: DetailRoutingLogic {
    func navigate(from source: BaseViewController, to destination: BaseViewController) {
        
    }
    
    func present(from source: BaseViewController, to destination: BaseViewController) {
        
    }
}
