//
//  DetailInteractor.swift
//  mApp
//
//  Created by Bahadır Enes Atay on 26.07.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailBusinessLogic {
    func fetchDetail(request: ContentDetailRequest)
}

class DetailInteractor {
    var presenter: DetailPresentationLogic?

}

extension DetailInteractor: DetailBusinessLogic {
    func fetchDetail(request: ContentDetailRequest) {
        Task {
            let response = await DetailWorker().fetchSelectedMovie(request)
            
            if let error = response.error {
                DispatchQueue.main.async {
                    self.presenter?.presentError(error.localizedDescription)
                }
            }
            
            if let detailModel = response.model {
                let response = Detail.FetchRequest.Response(content: detailModel)
                DispatchQueue.main.async {
                    self.presenter?.presentDetail(response: response)
                }
            }
        }
    }
}

