//
//  DetailWorker.swift
//  mApp
//
//  Created by Bahadır Enes Atay on 26.07.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class DetailWorker {
    func fetchSelectedMovie(_ req: ContentDetailRequest) async -> (model: ContentDetailResponse?, error: Error?) {
        do {
            let params = req.convertToDictionary()
            let data = try await RequestManager.request(.series, params)
            let model = try JSONDecoder().decode(ContentDetailResponse.self, from: data)
            return (model: model, error: nil)
        } catch {
            return (model: nil, error: error)
        }
    }
}
