//
//  DetailModels.swift
//  mApp
//
//  Created by Bahadır Enes Atay on 26.07.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Detail {
    // MARK: Use cases
    
    enum FetchRequest {
        struct Request {
            var digitalContentReq: ContentDetailRequest
        }
        
        struct Response {
            var content: ContentDetailResponse
        }
        
        struct ViewModel {
            struct ContentData {
                var image: String
                var title: String
                var year: String
                var rating: String
                var director: String
                var writer: String
                var genre: String
                var awards: String
                var production: String
                var type: String
                var runtime: String
                var plot: String
            }
            var contentData: ContentData
            
      
        }
    }
}
