//
//  ContentListInteractor.swift
//  mApp
//
//  Created by Bahadır Enes Atay on 25.07.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//


import UIKit

protocol ContentListInteractorInput: AnyObject {
    func getContents(request: SeriesRequest)
}

class ContentListInteractor {
    var presenter: ContentListPresentationLogic?
}

extension ContentListInteractor: ContentListInteractorInput {
    func getContents(request: SeriesRequest) {
        ContentListWorker().getMovies(request, onSuccess: { [weak self] series in
            self?.presenter?.presentSeries(response: ContentList.FetchRequest.Response(series: series.search, keyword: request.series!))
        }, onError: { [weak self] error in
            self?.presenter?.presentError(error)
        })
    }
}

//enum ContentListError: LocalizedError {
//    case contentNotFound(String)
//
//    var description: String {
//        switch self {
//        case .contentNotFound(let keyword):
//            return String(format: AppLocalization.text(.HOME_NO_RESULT_ALERT_TEXT), keyword)
//        }
//    }
//}
