//
//  ContentListPresenter.swift
//  mApp
//
//  Created by Bahadır Enes Atay on 25.07.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ContentListPresentationLogic: AnyObject {
    func presentSeries(response: ContentList.FetchRequest.Response)
    func presentError(_ error: String)
}

class ContentListPresenter {
    var viewController: ContentListDisplayLogic?
        
}

extension ContentListPresenter: ContentListPresentationLogic {
    func presentSeries(response: ContentList.FetchRequest.Response) {
        let contentList = response.series
            .filter{$0.title != nil && $0.year != nil && $0.poster != nil && $0.imdbID != nil}
            .map{ return ContentList.FetchRequest.ViewModel.SeriesData(name: $0.title!, year: $0.year!, image: $0.poster!, id: $0.imdbID!) }
        let viewModel = ContentList.FetchRequest.ViewModel(keyword: response.keyword, seriesData: contentList)
        viewController?.displaySeries(viewModel)
    }
    
    func presentError(_ error: String) {
        viewController?.displayError(error)
    }
}
