//
//  ContentListRouter.swift
//  mApp
//
//  Created by Bahadır Enes Atay on 25.07.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ContentListRoutingLogic {
    func navigate(from source: BaseViewController, to destination: BaseViewController)
    func present(from source: BaseViewController, to destination: BaseViewController)
}

//protocol ContentListDataPassing {
//    var dataStore: ContentListDataStore? { get }
//}

class ContentListRouter: NSObject {
    var viewController: ContentListViewController?
//    var dataStore: ContentListDataStore?
}

extension ContentListRouter: ContentListRoutingLogic {
    func navigate(from source: BaseViewController, to destination: BaseViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    func present(from source: BaseViewController, to destination: BaseViewController) {
        source.navigationController?.present(destination, animated: true, completion: nil)
    }
}

