//
//  ContentListWorker.swift
//  mApp
//
//  Created by Bahadır Enes Atay on 25.07.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ContentListWorker {
    
    func fetchSeries(_ req: SeriesRequest) async -> (model: SeriesResponse?, error: Error?) {
        await RequestManager.cancelRequest()
        let model = Task { () -> SeriesResponse in
            let params = req.convertToDictionary()
            let data = try await RequestManager.request(.series, params)
            return try JSONDecoder().decode(SeriesResponse.self, from: data)
        }
        
        do {
            return try await (model: model.value, error: nil)
        } catch {
            return (model: nil, error: error)
        }
    }
}


enum APIError: LocalizedError {
    case dataNotFound
    
    var description: String {
        switch self {
        case .dataNotFound:
            return "Data Not Found"
        }
    }
    
    
}
