//
//  ContentListInteractor.swift
//  mApp
//
//  Created by Bahadır Enes Atay on 25.07.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//


import UIKit

protocol ContentListInteractorInput: AnyObject {
    func fetchContents(request: SeriesRequest)
}

class ContentListInteractor {
    var presenter: ContentListPresentationLogic?
}

extension ContentListInteractor: ContentListInteractorInput {
    func fetchContents(request: SeriesRequest) {
        Task {
            let response = await ContentListWorker().fetchSeries(request)

            if let seriesModel = response.model, let keyword = request.series {
                let response = ContentList.FetchRequest.Response(series: seriesModel.search ?? [], keyword: keyword)
                DispatchQueue.main.async {
                    self.presenter?.presentSeries(response: response)
                }
            }
            
            if let error = response.error {
                DispatchQueue.main.async {
                    self.presenter?.presentError(error.localizedDescription)
                }
            }
        }
    }
}
